// Package worker implements the queue processing loop for Ralph.
package worker

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os/exec"
	"regexp"
	"strings"
	"time"

	"github.com/arvesolland/ralph/internal/git"
	"github.com/arvesolland/ralph/internal/log"
	"github.com/arvesolland/ralph/internal/prompt"
	"github.com/arvesolland/ralph/internal/runner"
)

// Common completion errors.
var (
	// ErrGHNotInstalled is returned when the GitHub CLI is not available.
	ErrGHNotInstalled = errors.New("gh CLI not installed")

	// ErrPushFailed is returned when pushing the branch fails.
	ErrPushFailed = errors.New("failed to push branch")

	// ErrPRCreateFailed is returned when creating the PR fails.
	ErrPRCreateFailed = errors.New("failed to create PR")

	// ErrMergeConflict is returned when merge has conflicts.
	ErrMergeConflict = errors.New("merge conflict")

	// ErrCheckoutFailed is returned when checkout fails.
	ErrCheckoutFailed = errors.New("failed to checkout branch")

	// ErrMergeFailed is returned when merge fails (non-conflict).
	ErrMergeFailed = errors.New("failed to merge branch")
)

// prURLRegex matches the PR URL from gh pr create output.
var prURLRegex = regexp.MustCompile(`https://github\.com/[^/]+/[^/]+/pull/\d+`)

// PRCreationTimeout is the timeout for Claude to create the PR.
const PRCreationTimeout = 5 * time.Minute

// pushBranch pushes the branch to origin with upstream tracking.
func pushBranch(g git.Git, branch string) error {
	return g.PushWithUpstream("origin", branch)
}

// createPRSimple creates a PR using Claude CLI to generate description.
// Takes simple params instead of plan.Plan / worktree.Worktree.
func createPRSimple(title, branch, workDir string, r runner.Runner, pb *prompt.Builder) (string, error) {
	if !isGHInstalled() {
		return "", ErrGHNotInstalled
	}

	// Try Claude-generated PR first
	prURL, err := createPRWithClaude(title, branch, workDir, r, pb)
	if err != nil {
		// Fall back to basic PR creation
		log.Warn("Claude PR creation failed: %v, falling back to basic PR", err)
		prURL, err = createPRBasic(title, workDir)
		if err != nil {
			return "", fmt.Errorf("%w: %v", ErrPRCreateFailed, err)
		}
	}

	return prURL, nil
}

// createPRWithClaude uses Claude Code CLI to create a PR with a good description.
func createPRWithClaude(title, branch, workDir string, r runner.Runner, pb *prompt.Builder) (string, error) {
	overrides := map[string]string{
		"FEATURE_BRANCH": branch,
		"BASE_BRANCH":    "main",
	}

	promptContent, err := pb.Build("pr_creation_prompt.md", overrides)
	if err != nil {
		return "", fmt.Errorf("building PR prompt: %w", err)
	}

	opts := runner.DefaultOptions()
	opts.WorkDir = workDir
	opts.NoPermissions = true
	opts.AllowedTools = []string{"Bash", "Read", "Glob", "Grep"}

	ctx, cancel := context.WithTimeout(context.Background(), PRCreationTimeout)
	defer cancel()

	result, err := r.Run(ctx, promptContent, opts)
	if err != nil {
		return "", fmt.Errorf("claude execution: %w", err)
	}

	// Extract PR URL from Claude's output
	prURL := extractPRURL(result.TextContent)
	if prURL == "" {
		prURL, _ = getExistingPRURL(workDir)
	}

	if prURL == "" {
		return "", fmt.Errorf("PR may have been created but URL not found in output")
	}

	return prURL, nil
}

// createPRBasic creates a PR using the gh CLI with basic title/body (fallback).
func createPRBasic(title, workDir string) (string, error) {
	if !isGHInstalled() {
		return "", ErrGHNotInstalled
	}

	prTitle := fmt.Sprintf("feat: %s", title)
	body := fmt.Sprintf("## Summary\n\nImplements: %s\n\n---\n\nGenerated by [Ralph](https://github.com/arvesolland/ralph)", title)

	cmd := exec.Command("gh", "pr", "create",
		"--title", prTitle,
		"--body", body,
	)
	cmd.Dir = workDir

	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		errOutput := stderr.String()

		if strings.Contains(errOutput, "already exists") {
			return getExistingPRURL(workDir)
		}

		return "", fmt.Errorf("gh pr create: %s: %w", errOutput, err)
	}

	output := stdout.String()
	prURL := extractPRURL(output)
	if prURL == "" {
		prURL = extractPRURL(stderr.String())
	}

	if prURL == "" {
		prURL = strings.TrimSpace(output)
	}

	return prURL, nil
}

// isGHInstalled checks if the GitHub CLI is available.
func isGHInstalled() bool {
	_, err := exec.LookPath("gh")
	return err == nil
}

// extractPRURL extracts a GitHub PR URL from text.
func extractPRURL(text string) string {
	match := prURLRegex.FindString(text)
	return match
}

// getExistingPRURL gets the URL of an existing PR for the current branch.
func getExistingPRURL(workDir string) (string, error) {
	cmd := exec.Command("gh", "pr", "view", "--json", "url", "-q", ".url")
	cmd.Dir = workDir

	var stdout bytes.Buffer
	cmd.Stdout = &stdout

	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("getting existing PR: %w", err)
	}

	return strings.TrimSpace(stdout.String()), nil
}

// logManualPRInstructionsSimple logs instructions for creating PR manually.
func logManualPRInstructionsSimple(name, branch string) {
	log.Warn("GitHub CLI (gh) not installed. Please create PR manually:")
	log.Info("  1. Go to your repository on GitHub")
	log.Info("  2. Create a new pull request for branch: %s", branch)
	log.Info("  3. Or install gh: https://cli.github.com/")
}

// CompleteBranch handles branch mode completion:
// Push branch to origin only, without creating a PR.
func CompleteBranch(branch, baseBranch string, g git.Git) error {
	log.Info("Pushing branch %s to origin...", branch)
	if err := pushBranch(g, branch); err != nil {
		return fmt.Errorf("%w: %v", ErrPushFailed, err)
	}
	log.Success("Branch %s pushed to origin (no PR created)", branch)
	return nil
}

// CompleteMerge handles merge mode completion:
// 1. Check out base branch in main worktree
// 2. Merge feature branch with --no-ff
// 3. Push base branch to origin
// 4. Delete feature branch (local and remote)
func CompleteMerge(featureBranch, baseBranch string, mainGit git.Git) error {
	// Step 1: Checkout base branch
	log.Info("Checking out base branch %s...", baseBranch)
	if err := mainGit.Checkout(baseBranch); err != nil {
		return fmt.Errorf("%w: %v", ErrCheckoutFailed, err)
	}
	log.Debug("Checked out %s", baseBranch)

	// Step 2: Merge feature branch with --no-ff
	log.Info("Merging %s into %s...", featureBranch, baseBranch)
	if err := mainGit.Merge(featureBranch, true); err != nil {
		if errors.Is(err, git.ErrMergeConflict) {
			return fmt.Errorf("%w: resolve conflicts in %s and try again", ErrMergeConflict, baseBranch)
		}
		return fmt.Errorf("%w: %v", ErrMergeFailed, err)
	}
	log.Success("Merged %s into %s", featureBranch, baseBranch)

	// Step 3: Push base branch to origin
	log.Info("Pushing %s to origin...", baseBranch)
	if err := mainGit.Push(); err != nil {
		return fmt.Errorf("%w: %v", ErrPushFailed, err)
	}
	log.Success("Pushed %s to origin", baseBranch)

	// Step 4: Delete feature branch (local)
	log.Info("Deleting local branch %s...", featureBranch)
	if err := mainGit.DeleteBranch(featureBranch, true); err != nil {
		log.Warn("Failed to delete local branch %s: %v", featureBranch, err)
	} else {
		log.Debug("Deleted local branch %s", featureBranch)
	}

	// Step 5: Delete feature branch (remote)
	log.Info("Deleting remote branch %s...", featureBranch)
	if err := mainGit.DeleteRemoteBranch("origin", featureBranch); err != nil {
		log.Warn("Failed to delete remote branch %s: %v", featureBranch, err)
	} else {
		log.Debug("Deleted remote branch %s", featureBranch)
	}

	log.Success("Merge complete: %s merged into %s", featureBranch, baseBranch)
	return nil
}
